### ISSUE TITLE
Configuration error whilst installing via cabal

### ISSUE THREAD

**Issue by leaffan** [ivan-m/graphviz#32] opened 2018-05-17 08:51 UTC
Trying to install graphviz via cabal (using *cabal install graphviz*), I'm encountering multiple errors in the following form:

```
[ 7 of 31] Compiling Data.GraphViz.Printing ( Data\GraphViz\Printing.hs, dist\build\Data\GraphViz\Printing.o )

Data\GraphViz\Printing.hs:232:16: error:
    Ambiguous occurrence `<>'
    It could refer to either `Prelude.<>',
                             imported from `Prelude' at Data\GraphViz\Printing.hs:48:8-29
                             (and originally defined in `GHC.Base')
                          or `PP.<>',
                             imported from `Text.PrettyPrint.Leijen.Text.Monadic' at Data\GraphViz\Printing.hs:(75,1)-(81,68)
    |
232 | wrap b a d = b <> d <> a
    |                ^^
```
Is this an issue that can be solved by adjusting my environment?

**Comment by ivan-m** [comment] 2018-05-17 11:31
Duplicate of #30 

Unfortunately I don't have a working release compatible with 8.4 yet; life keeps getting in the way.

I may be able to work on it during LambaJAM next week.

**Closed by ivan-m** 2018-05-17 11:31 UTC
